config/routes.rb
Kolkominate::Application.routes.draw do

  get "categories" => "categories#index", as: :categories
  get "category/:id" => "categories#show", as: :category

  resources :expenses

  get "public/index"

  devise_for :users do
	  get "/signin" => "devise/sessions#new", :as => :signin
	  get "/signout" => "devise/sessions#destroy", :as => :signout
    get "/signup" => "devise/registrations#new", :as => :signup
  end

  root :to => 'public#index'

end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :expenses
end

app/models/expense.rb
class Expense < ActiveRecord::Base
	validates :value, :date, :presence => true
	validates :value, :numericality => { greater_than_or_equal_to: 0.01 }
	validates :description, :length => { maximum: 500 }

	attr_accessible :value, :date, :description

	belongs_to :user
	belongs_to :currency

	attr_taggable :categories

	def value=(value)
		write_attribute(:value,value.sub(",","."))
	end

	def self.date_between(from,to)
		from = '01.01.2012' if from.blank?
		to = Time.now.strftime("%d.%m.%Y") if to.blank?
		where(date: (from.to_date..to.to_date))
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

	has_many :expenses, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	def after_sign_in_path_for(resource)
		stored_location_for(resource) || expenses_path
	end

	def after_sign_out_path_for(resource)
		root_path
	end

  unless Rails.configuration.consider_all_requests_local
    rescue_from Exception, :with => :render_error
    rescue_from ActiveRecord::RecordNotFound, :with => :render_not_found
    rescue_from ActionController::RoutingError, :with => :render_not_found
    rescue_from ActionController::UnknownController, :with => :render_not_found
    rescue_from ActionController::UnknownAction, :with => :render_not_found
  end

  private

    def render_not_found(exception)
      #log_error(exception)
      render :template => "/error/404.html.erb", :status => 404
    end

    def render_error(exception)
      #log_error(exception)
      render :template => "/error/500.html.erb", :status => 500
    end    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authenticate_user!

  # GET /categories
  def index
    @categories = RocketTag::Tagging.select('*, COUNT(taggable_id) AS taggable_cnt').where("tagger_id=#{current_user.id} AND context='categories'").group('tag_id')

    if params[:sort] == "expenses"
      @categories = @categories.order('taggable_cnt DESC')
    end

    respond_to do |format|
      format.html
      format.json do
        ctgs = ActiveRecord::Base.connection.execute("SELECT DISTINCT t.id, t.name FROM tags t RIGHT JOIN taggings ts ON ts.tag_id=t.id WHERE ts.tagger_id=#{current_user.id} AND t.name LIKE '#{params['q']}%' ORDER BY name")
        render json: ctgs.map {|i| {id: i[1], name: i[1]} }
      end
    end
  end

  # GET /category/1
  def show
    @category = RocketTag::Tag.find(params[:id])
    @taggings = @category.taggings.where("context='categories'")#.where("tagger_id=#{current_user.id}")

    # chceme zobrazit zoznam vsetkych Expensov patriacich akt. userovi AND majucich aktualny tag ako kategoriu
    @expenses = Expense.tagged_with([@category.name],on: "categories").where("user_id=#{current_user.id}").order("date DESC")
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

	before_filter :authenticate_user!

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = current_user.expenses.date_between(params[:from],params[:to]).order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expenses }
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.json
  def new
    @expense = Expense.new
    @assigned_categories = ""

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
	  @assigned_categories = @expense.categories.join(",")
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(params[:expense])
    unless @expense.date
      @expense.date = Time.now.to_s[0,10]
    end
    @expense.currency_id = Currency.find_by_name('Euro').id
    @expense.user_id = current_user.id
    @expense.categories = params[:categories].split(',')

    respond_to do |format|
      if @expense.save
        add_tagger_to_taggings(@expense)
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.json
  def update
	  @expense = Expense.find(params[:id])
	  @expense.categories = params[:categories].split(',')

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        add_tagger_to_taggings(@expense)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :ok }
    end
  end

  private

    def add_tagger_to_taggings(expense)
      RocketTag::Tagging.where("taggable_type='Expense' AND taggable_id=#{expense.id}").each do |tagging|
        tagging.update_attributes({tagger_id: current_user.id, tagger_type: "User"})
      end
    end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
	  render layout: "public"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def main_menu_item_for(path, text, alt, img_name)
    if current_page?(path)
      link_to content_tag(:strong, image_tag("/images/nav/#{img_name}", alt: alt) + " #{text}"), path
    else
      link_to image_tag("/images/nav/#{img_name}", alt: alt) + " #{text}", path
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper

  def categories_links_for(expense)
    expense.categories.map do |ctg_name|
      ctg = RocketTag::Tag.find_by_name(ctg_name)
      link_to ctg.name, category_path(ctg.id)
    end.join(", ").html_safe
  end

end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/index.html.erb
<h2>Výdavky podľa kategórií</h2>

<p>
  <%= link_to "Zoradiť podľa abecedy", categories_path, class: "demo_custom" %> |
  <%= link_to "Zoradiť podľa počtu výdavkov", categories_path(sort: "expenses"), class: "demo_custom" %>
</p>

<% @categories.each do |ctg| %>
<% ctg_expenses = Expense.tagged_with([ctg.tag.name], :on => "categories") %>
<div class="textbox half">
  <h2><%= ctg.tag.name %></h2>
  <div class="textbox_content">
    Počet výdavkov v kategórii: <%= ctg_expenses.count %><br />
    Posledný výdavok v kategórii: <%= ctg_expenses.last.date %>: <%= ctg_expenses.last.value %> <%= ctg_expenses.last.currency.symbol.html_safe %><br />
    <%= link_to "Zobraziť prehľad kategórie", category_path(ctg.tag_id) %>
  </div>
</div>
<% end %>

app/views/categories/show.html.erb
<h2>Výdavky v kategórií <%= @category.name %></h2>

<% start_new_block = true %>
<% @expenses.each_with_index do |exp, index| %>
  <% if start_new_block %>
    <% start_new_block = false %>
    <div class="textbox half">
      <h2><%= exp.date %></h2>
  <% end %>
      <div class="textbox_content">
        <strong><%= exp.value %> <%= exp.currency.symbol.html_safe %></strong>
        <%= " - #{exp.description}" unless exp.description.blank? %>
      </div>
  <% if @expenses[index+1].nil? or @expenses[index+1].date!=exp.date %>
    <% start_new_block = true %>
    </div>
  <% end %>
<% end %>

<p><%= link_to 'Na zoznam kategórií', categories_path %></p>

app/views/expenses/_expense.html.erb
<tr class="<%= cycle("even","odd") %>">
  <td><%= expense.value %> <%= expense.currency.symbol.html_safe %></td>
  <td><%= expense.date.strftime('%d.%m.%Y') %></td>
  <td><%= categories_links_for(expense) %></td>
  <td>
    <%= link_to 'Detaily', expense %> |
    <%= link_to 'Upraviť', edit_expense_path(expense) %> |
    <%= link_to 'Zmazať', expense, confirm: 'Ste si istý?', method: :delete %>
  </td>
</tr>

app/views/expenses/_form.html.erb
<%= render 'shared/form_errors', target: @expense %>

<%= form_for(@expense) do |f| %>
  <div class="field">
    <%= f.label :value, "Suma" %><br />
    <%= f.text_field :value, :size=>8 %> &euro;
  </div>
  <div class="field">
    <%= f.label :date, "Dátum" %><br />
    <%= f.text_field :date, :class=>"text date_picker" %>
  </div>
	<div class="field">
    <%= f.label :categories, "Kategórie oddelené čiarkami" %><br />
    <%= text_field_tag :categories, @assigned_categories, :size=>100, :class=>'text' %>
  </div>
  <div class="field">
    <%= f.label :description, "Popis" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit "Uložiť" %>
  </div>
<% end %>

app/views/expenses/create.js.erb
<% unless @expense.errors.any? %>
  $('div.new-expense-form .errors').text('');
  $('#expenses-list tbody').prepend('<%= escape_javascript(render @expense) %>');
  $('#expense_value').val('');
  $('#categories').val('');
  $('#categories').tokenInput("clear");
<% else %>
  <% if @expense.errors.messages[:value].include?("can't be blank") %>
    $('div.new-expense-form .errors').text("Zabudli ste zadať cenu!");
  <% elsif @expense.errors.messages[:value].include?("is not a number") %>
    $('div.new-expense-form .errors').text("Cena musí byť číslo!");
  <% else %>
  $('div.new-expense-form .errors').text("Nastala chyba pri ukladaní výdavku. Prosím, skúste to znova.");
  <% end %>
<% end %>

app/views/expenses/edit.html.erb
<h2>Upraviť výdavok</h2>

<%= render 'form' %>

<%= link_to 'Zobraziť', @expense %> |
<%= link_to 'Späť', expenses_path %>

app/views/expenses/index.html.erb
<h2>Výdavky (<%= link_to '+', new_expense_path %>)</h2>

<%= render partial: 'shared/add_expense_form' %>

<%= render partial: 'shared/limit_expenses_form', locals: { action:'/expenses' } %>

<table cellpadding="0" cellspacing="0" width="100%" class="sortable" id="expenses-list">
  <thead>
    <tr>
      <th>Suma</th>
      <th>Dátum</th>
      <th>Kategórie</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: @expenses %>
  </tbody>
</table>

app/views/expenses/new.html.erb
<h2>Nový výdavok</h2>

<%= render 'form' %>

<%= link_to 'Späť', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Výdavok:</b>
  <%= @expense.value %> <%= @expense.currency.symbol.html_safe %>
</p>

<p>
  <b>Dátum:</b>
  <%= @expense.date.strftime('%d.%m.%Y') %>
</p>

<% if @expense.categories %>
<p>
  <b>Kategórie:</b>
  <%= @expense.categories.join(", ") %>
</p>
<% end %>

<% if @expense.description %>
<p>
  <b>Popis:</b>
  <%= @expense.description %>
</p>
<% end %>

<%= link_to 'Upraviť', edit_expense_path(@expense) %> |
<%= link_to 'Späť', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=7" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="." />
	<meta name="keywords" content="." />

	<title>Kolkominate.sk</title>

  <%= stylesheet_link_tag "application" %>

	<!--[if lt IE 9]>
	<%= stylesheet_link_tag "ie" %>
	<![endif]-->

	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

	<div id="header">
		<h1><a href="#">Kolkominate.sk</a></h1>
		<% if user_signed_in? %>
		  <div class="userprofile">
			<ul>
				<li><a href="#"><%= image_tag "/images/avatar.gif" %> <%= current_user.email %></a>
					<ul>
						<li><%= link_to "Odhlásiť sa", signout_path %></li>
					</ul>
				</li>
			</ul>
		</div>		<!-- .userprofile ends -->
		<% end %>
	</div>			<!-- #header ends -->

	<div id="sidebar">
	  <ul id="nav">
	    <li>
	    	<%= main_menu_item_for expenses_path, "Výdavky", "Chronologický prehľad výdavkov", "dashboard.png" %>
	    	<ul>
	    		<li><%= link_to 'Pridať výdavok', new_expense_path %></li>
	    	</ul>
	    </li>
      <li><%= main_menu_item_for categories_path, "Kategórie", "Výdavky podľa kategórií", "support.png" %></li>
	  </ul>
	</div>

	<div id="content">

	  <div class="breadcrumb">
		  <%= link_to "Home", expenses_path %>
	  </div>

		<% if flash[:notice] %>
			<div class="message info" style="display: block;">
			  <%= flash[:notice] %>
		<% end  %>
		<% if flash[:alert] %>
			<div class="message errormsg" style="display: block;">
			  <%= flash[:alert] %>
		<% end %>
		<% if flash[:success] %>
			<div class="message sucess" style="display: block;">
			  <%= flash[:success] %>
		<% end %>
		<% unless flash.empty? %>
				<span class="close" title="Dismiss"></span>
			</div>
		<% end %>

	  <%= yield %>
	</div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=7" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="." />
	<meta name="keywords" content="." />

	<title>Kolkominate.sk</title>

  <%= stylesheet_link_tag "application" %>

	<!--[if lt IE 9]>
	<%= stylesheet_link_tag "ie" %>
	<![endif]-->

	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class="loginpage">

	<div id="header">
		<h1><a href="#">Kolkominate.sk</a></h1>
	</div>			<!-- #header ends -->

	<div id="content" class="loginbox">
		<% if flash[:notice] %>
			<div class="message info" style="display: block;">
			  <%= flash[:notice] %>
		<% end  %>
		<% if flash[:alert] %>
			<div class="message errormsg" style="display: block;">
			  <%= flash[:alert] %>
		<% end %>
		<% if flash[:success] %>
			<div class="message sucess" style="display: block;">
			  <%= flash[:success] %>
		<% end %>
		<% unless flash.empty? %>
				<span class="close" title="Dismiss"></span>
			</div>
		<% end %>

	  <%= yield %>
	</div>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=7" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="." />
	<meta name="keywords" content="." />

	<title>Kolkominate.sk</title>

  <%= stylesheet_link_tag "public" %>
	<%= javascript_include_tag "public" %>

  <%= csrf_meta_tags %>
</head>

<body>

	<%= link_to "Prihláste sa", signin_path %> alebo sa <%= link_to "zaregistrujte", signup_path %>

	<div id="content">
		<% if flash[:notice] %>
			<div class="message info" style="display: block;">
			  <%= flash[:notice] %>
		<% end  %>
		<% if flash[:alert] %>
			<div class="message errormsg" style="display: block;">
			  <%= flash[:alert] %>
		<% end %>
		<% if flash[:success] %>
			<div class="message sucess" style="display: block;">
			  <%= flash[:success] %>
		<% end %>
		<% unless flash.empty? %>
				<span class="close" title="Dismiss"></span>
			</div>
		<% end %>
		
		<%= yield %>
	</div>

</body>
</html>

app/views/shared/_add_expense_form.html.erb
<div class="new-expense-form quickformbox">
  <div class="errors"></div>
  <%= form_for Expense.new, remote: true do |f| %>
  	<span>Pridať výdavok</span>
    <%= f.text_field :value, size: 8 %> 
    <span>&euro; &nbsp;&nbsp;&nbsp; do kategórií</span> <%= text_field_tag :categories, '', :size=>85, :class=>'text' %>
  	<%= f.submit "Uložiť" %>
  <% end %>
</div>

<script type="text/javascript">
$(function() {
  $('#categories').tokenInput('/categories.json',{
    crossDomain: false,
    theme: 'adminium',
    hintText: 'Sem napíšte kategórie výdavku',
    searchingText: 'Hľadá sa...',
    noResultsText: 'Táto kategória zatiaľ neexistuje.'
  });
});
</script>

app/views/shared/_form_errors.html.erb
<% if target.errors.any? %>
	<h3>Uloženiu zabraňujú nasledujúce chyby:</h3>
	<div class="message errormsg">
		<% target.errors.full_messages.each do |msg| %>
			<p>
				<%= msg %>
			</p>
		<% end %>
	</div>
<% end %>

app/views/shared/_limit_expenses_form.html.erb
<div class="limit-expenses-form quickformbox">
  <%= form_tag(action, method:'get') do %>
    <%= label_tag(:from, "Zobraziť len výdavky od:") %>
    <%= text_field_tag(:from, params[:from], :class=>"text date_picker") %>
    <%= label_tag(:to, "do:") %>
    <%= text_field_tag(:to, params[:to], :class=>"text date_picker") %>
  <%= submit_tag("Zobraziť", :class=>"submit") %> <%= link_to 'Zrušiť filter', action %>
  <% end %>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>